{
"hide_panel":true,
"show_startpage":false,
"show_stoppage":false,
"keys_play":"",
"keys_pause":"",
"keys_stop":"esc",
"keys_show_highlight":"f1",
"scorm_tracking":"completion",
"aicc_tracking":"none",
"ok":true}
